name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 22
          cache: yarn

      - run: yarn install --immutable

      - name: Validate extensions.json
        run: yarn validate
